### ISSUE TITLE
REST api should expose api/conferences/confId/talks so talks can be fetched after acceptance before schedule planning is done

### ISSUE THREAD

**Issue by ge0ffrey** [nicmarti/cfp-devoxx#1]
All DevoxxBE 2015 talks are now accepted, but we can't fetch them yet, because this URL isn't available:
  http://cfp.devoxx.be/api/conferences/DV15/talks

So I can't fetch them into OptaConf and propose an optimized planning (=> rock stars get better rooms, no 2 talks of the same track at the same time, etc).

**Comment by nicmarti** [comment]
Hi Geoffrey

There is a difference between a talk being accepted and scheduled.

See the list of schedules here :
http://cfp.devoxx.be/api/conferences/DV15/schedules/

The agenda for Wednesday will be available here: http://cfp.devoxx.be/api/conferences/DV15/schedules/wednesday/

The list of rooms that you need:
http://cfp.devoxx.be/api/conferences/DV15/rooms

However the Devoxx BE team has not yet created a Schedule and started to configure talks and rooms. Until then, you won't be able to load and to check a schedule.

Can you contact them and ask them to start to build a Schedule with the integrated CFP Angular application? Then you will be able to retrieve the active schedule. 

If in return your application is supposed to optimize all schedules (rooms, speakers, etc) then you will need a new endpoint to "post" a full agenda (list of schedules). This is not yet implemented and will require further discussions. 

Thanks for your work

Nicolas

**Comment by ge0ffrey** [comment]
OptaConf is an open source app that reads the talks _before_ they are scheduled (only accepted talks of course) and suggest a way to _automatically_ schedule them while optimizing certain constraints.

So we can't wait until the talks are scheduled - that would be a chicken and egg problem :) See also the bottom of this blog post: http://www.optaplanner.org/blog/2014/11/17/Prototyping-a-full-webapp-at-Devoxx-hackergarten.html

**Comment by ge0ffrey** [comment]
PS: Once OptaConf (Apache License) works well, it might be interesting to copy paste it for your Angular app that builds a schedule, by adding a button "suggest schedule".

**Comment by ge0ffrey** [comment]
But for now, for phase 1, OptaConf just pulls the schedule, optimizes it and the they'll have to manually fill that back into this app - which should be reasonable.

**Comment by nicmarti** [comment]
Ok I understand.
You need a list of Accepted Proposals. I implemented the /talks endpoint so that it returns what you are looking for.

See
http://cfp.devoxx.be/api/conferences/DV15/talks

FYI the workflow for a Proposal is the following : 
SUBMITTED -> APPROVED (by technical committee) -> ACCEPTED (by the speaker)

You should planify only accepted talks (and not approved)
One speaker can have 3 APPROVED Talks, but he can then keep only two (set to ACCEPTED) and decline the third one.

Hope it helps, enjoy.

**Comment by ge0ffrey** [comment]
Great stuff, this works :)

Thank you!
