### ISSUE TITLE
The default user First Name and Last Name will not be updated after change

### ISSUE THREAD

**Issue by amczarny** [nicmarti/cfp-devoxx#100]
I have saved my profile with default Devoxx CFP (why there is a default for first and last name). The update of my first name and last name in profile has no effect. e.g. My submitted talk has Devoxx CFP as a Speaker (I have to create a new profile).
The update of you the profile first name and last name should update all the references to the speaker.

**Comment by aheritier** [comment]
Hi @amczarny,

  How did you authenticate to create your account ? Using GitHub ? 
  We have several users reporting different issues with the authentication, we are still investigating but I think your problem could be related to it

BR

**Comment by amczarny** [comment]
Yes, I have initially authenticated with GitHub. To fix it I had to sign-up one more time with email, first name and last name.

**Comment by dwursteisen** [comment]
Hello, 

same here. 
In my profile, the name is correct, but on the CFP page, my name is "John Doe". If I change my name for something else, the name displayed on the main page is still John Doe.

I'm logged using Google authentification.

Regards.

**Comment by jerometambo** [comment]
Hey,

I signed up via Github and when I logged in the first time my firstname was Devoxx and my lastname was CFP : 
![image](https://user-images.githubusercontent.com/16915886/34774703-a458f680-f610-11e7-8c12-3e0e9fd8a3b3.png)

**Comment by aheritier** [comment]
It's strange cc @nicmarti 
You are several ones to have these erroneous settings after your first authentication
Can you confirm that after an edit/save of your profile the problem is fixed ?

**Comment by aheritier** [comment]
Another one today named Devoxx CFP

UUID : 962538e49cb1e0a98f9146ddc9eec236b8a43586

@gbloquel how did you create your account ? cc @slecache

**Comment by aheritier** [comment]
I fixed ~ 10 accounts called Devoxx CFP ..

**Comment by gbloquel** [comment]
Hi @aheritier

My account was created through Google authentication.

**Comment by nicmarti** [comment]
If your default firstname and lastname is "Devoxx CFP" this is due to 2017, where we had my.devoxx.fr OAuth service (now down). At this time, we created webuser through a REST API call. 
I removed this code but if your account was already here, that's the reason why it was "pre-filled"

There's no fix, please update your profile and set firstname/lastname to the correct value

Sorry for this inconvenience.
