### ISSUE TITLE
Golden ticket

### ISSUE THREAD

**Issue by stevehouel** [nicmarti/cfp-devoxx#109]
When we try to save an existing proposal with an update of Golden ticket status (disable it in my case), that information is not updated and saved.

**Comment by nicmarti** [comment]
Confirmed.
Speaker cannot "unflag" the "Golden ticket checkbox". Once we save the Proposal, it is reste to "Yes I  would like my proposal to be reviewed by Attendees with a Golden Ticket"

**Comment by nicmarti** [comment]
Fixed and deployed. 
Thanks for reporting.
