### ISSUE TITLE
Create user profile is failling with 'Error : Please check your profile, invalid webuser.'

### ISSUE THREAD

**Issue by sunix** [nicmarti/cfp-devoxx#110]
Having that:
 - I've signed in with oauth and my github account

When I create my account with

- email: `sutan@redhat.com`
- first name: `Sun`
- last name: `Tan`
- bio: `Senior Software Engineer @redhatsoftware. Codenvy/Eclipse Che committer. OpenSource Minded. @parisjug team`
- company: `Red Hat`
- twitter: `@sunsengdavidtan`
- blog: `http://blog.sunix.org`
- speaker qualification: 

```
2017
- Github Paris: Che demo show case
- EclipseCon Fr: Simplified Open Source Contributions with Che

2016 The Path to Pair Programming in Che
- CheConf
- JavaOne
- Devfest Nantes
- EclipseCon NA
- Snowcamp

2016
- JugSummerCamp: Simplified Open Source Contributions with Che

2015 Pair programming with Che, Eclipse IDE, Orion, Flux and Docker
 - EclipseCon Eu
 - EclipseCon Fr
 - JugSummerCamp

2015
- Devoxx Fr: Dévelopement Java avec un IDE Cloud: YES WE CAN
- EclipseCon Fr: Code in the cloud with Eclipse Che

2014
- EclipseCon EU: Introduction to Eclipse Che

2013
- Breizhcamp: BDD and Concordion
- Nuxeo World: Nx components and xpoints completion in NxIDE
- OW2Con: NoSQL Landscape

2008 Nuxeo Apogee
- EclipseCon EU
- Nuxeo DevDay
```

- avatar `http://www.gravatar.com/avatar/8a055e00e0e10b5ec2670fb956bade92`

Then,
- I have the error `'Error : Please check your profile, invalid webuser.'`
- I have the message `Maximum length is 750` next to speaker qualification where it's only 745 length

```
$ wc speakerxp.txt -c
745 speakerxp.txt
```

**Comment by sunix** [comment]
first the message is unclear "invalid webuser ...."
second, removing few characters from the speaker qualification field is validating the form

**Comment by nicmarti** [comment]
Hi
The first message is a generic message, generated by Play, with the Bad Request response.
The second one is the reason why it didn't work. 

I'll check why it won't validate with your content, this might be related to the Markdown plugin that generates the speaker's qualifications.

Thanks for reporting
