### ISSUE TITLE
LinkedIn federated signin not working

### ISSUE THREAD

**Issue by shahiddev** [nicmarti/cfp-devoxx#112]
Error when trying to sign up as speaker using LinkedIn
![image](https://user-images.githubusercontent.com/11890711/34677855-52ca76c8-f489-11e7-879f-fe4ea61f9add.png)

**Comment by nicmarti** [comment]
Which CFP ? 
can you please specify what is the CFP URL ? 
Thanks

**Comment by shahiddev** [comment]
Apologies for the shoddy issue!
It was Devoxx
https://cfp.devoxx.co.uk/signup
