### ISSUE TITLE
Sponsor flag is not removed if ProposalType is updated from "Conference" to another format

### ISSUE THREAD

**Issue by nicmarti** [nicmarti/cfp-devoxx#113]
How to reproduce : 

- create a new proposal of type "Conference" and select "This is a sponsor/exhibitor talk"
- save and submit the talk
- edit the talk and change the Proposal type to another format (like University)
- the "sponsor" flag should be removed as only "Conference" are eligible as sponsor/exhibitor talks

This is a bit specific to Devoxx, we just need to have a look at the saveProposal function in CFPAdmin.

**Comment by nicmarti** [comment]
This is a very low priority bug

**Comment by aheritier** [comment]
yes not important. I'll review all sponsors talks with you

**Comment by nicmarti** [comment]
Fixed and deployed. Thanks for this bug report.
