### ISSUE TITLE
How to add poster section and round table?

### ISSUE THREAD

**Issue by ademulu** [nicmarti/cfp-devoxx#115]
Hi,
My name is Adem. I am using Cfp and I have a question to one subject.
I would like to add a new field outside of the following.

- Keynote
- Conference
- Quickie 
- Other

How can  I do this ?
Have a good work.

**Comment by nicmarti** [comment]
Hi Adem
Thanks for your question, however Github Issues are not here to answer questions, please do not submit your questions here. 

Look at ConferenceDescriptor, this is the class that needs to be updated.
ProposalType is also interesting. You will need a good level in Scala to understand and to update the application.
