### ISSUE TITLE
Edit a proposal is broken

### ISSUE THREAD

**Issue by aheritier** [nicmarti/cfp-devoxx#120]
Oops, an error occured
This exception has been logged with id `76j9gp1ei`.

**Comment by aheritier** [comment]
The error is: [RuntimeException: Missing CSRF Token]

views/html/CallForPaper/newProposal.template.scala:59

probably comes from c88e43922e48d81629446f10dcaa6b80c966dff6

**Comment by aheritier** [comment]
Reverting the usage of CSRF and especially this line restores the edition of the page

https://github.com/nicmarti/cfp-devoxx/commit/c88e43922e48d81629446f10dcaa6b80c966dff6#diff-4c55def19860d8b802a1b1d86df6066aR39

**Comment by aheritier** [comment]
Ok there is a workaround

If I do : login -> edit -> fail (because of CSRF)
If I do : login -> new proposal -> back -> edit -> ok

Doing a "new proposal" and back allows to workaround the bug

**Comment by nicmarti** [comment]
Updated.
The editProposal in CallForPaper Controller. CSRFCheck is not need in this action.

**Comment by nicmarti** [comment]
Deployed
