### ISSUE TITLE
Can't upload my photo

### ISSUE THREAD

**Issue by iAmDorra** [nicmarti/cfp-devoxx#149]
Hello, 

I commited a CFP but I can't upload a photo of my profile.
It asks me to put a URL but with a google drive URL or a OneDrive one that doesn't work.

How to upload a new photo please ?

Tks,
Dorra

**Comment by nicmarti** [comment]
Hi
Regarding the upload photo : this is a feature that we don't plan to implement for the CFP. We encourage you to use Gravatar (from your email address).
