### ISSUE TITLE
Filter by format

### ISSUE THREAD

**Issue by DrenBx** [nicmarti/cfp-devoxx#155]
Hello,

Since the main page pagination, the sort is a little bit useless and it's very complicated to review only all Quickies for example.
It's possible to add filters for formats on the main Admin page or make sorting globally?

Thanks,
FKA

**Comment by aheritier** [comment]
yes I shared a similar concern here : https://github.com/nicmarti/cfp-devoxx/pull/152
cc @nicmarti

**Comment by aheritier** [comment]
@nicmarti the pagination is making very difficult the verification that we reviewed all proposals of a given type

**Comment by DrenBx** [comment]
I just noticed, the Track filter doesn't works correctly, wrong format and already reviewed proposals are selected.

https://cl.ly/80c1bee6776d

**Comment by GabrielKast** [comment]
Same concern. Here is a strange example: https://cfp.devoxx.fr/cfpadmin?pageReview=1&sort=talkType&ascdesc=asc&track=lang
It appears that the first talk is a talk from last year.
Hope it helps tracking the bug - I wish I could have a look at it but don't have time now :/

**Comment by nicmarti** [comment]
Fixed, should now behave as expected.
