### ISSUE TITLE
CFP appears closed but the date is already Dec 2, 2019

### ISSUE THREAD

**Issue by adipolak** [nicmarti/cfp-devoxx#175]
it's Dec 2, 2019 and according to the schedule, we should be able to submit a CFP but on the website, it says that it is closed.
Can you please take a look?

Thanks!

![image](https://user-images.githubusercontent.com/2673267/69955235-e5a46f00-1505-11ea-95c8-7d7c80838008.png)

**Comment by aheritier** [comment]
Hi Adi,

  Yes the real date was supposed to be today (See PR #172 ) and we are now late. It will be open later today . We were a bit overwhelmed by the registration opening. Sorry.

Cheers

**Comment by aheritier** [comment]
Hi Adi.

  We fixed our dates (take care it's closing on January 12th) and we opened it.

Cheers

**Comment by adipolak** [comment]
thanks!

**Comment by aheritier** [comment]
@nicmarti can you close this issue please (was fixed)
