### ISSUE TITLE
My votes screen : displaying track statistics

### ISSUE THREAD

**Issue by fcamblor** [nicmarti/cfp-devoxx#208]
On BDX I/O, we implemented a summary of "my votes" stats compared allowing to give stats about :
- ourself
- and compare it to others (Comitee, GT, and overall)

Something like :

<table>
    <thead>
        <tr>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th colspan=4>Current type (Conferences)</th>
            <th colspan=4><em>All types</em></th>
        </tr>
        <tr>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>Me</th>
            <th>Comitee</th>
            <th>GT</th>
            <th>Overall</th>
            <th>Me</th>
            <th>Comitee</th>
            <th>GT</th>
            <th>Overall</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th rowspan=3>Current Track (Java JVM)</th>
            <th>Avg</th>
            <td>1.66</td>
            <td>2.66</td>
            <td>3.66</td>
            <td>4.66</td>
            <td>5.66</td>
            <td>6.66</td>
            <td>7.66</td>
            <td>8.66</td>
        </tr>
        <tr>
            <th>Stddev</th>
            <td> ± 0.1</td>
            <td>± 0.2</td>
            <td>± 0.3</td>
            <td>± 0.4</td>
            <td>± 0.5</td>
            <td>± 0.6</td>
            <td>± 0.7</td>
            <td>± 0.8</td>
        </tr>
        <tr>
            <th>Abs (%)</th>
            <td> 2 (4%)</td>
            <td> 10 (3%)</td>
            <td> 25 (5%)</td>
            <td> 265 (6%)</td>
            <td> 15 (4%)</td>
            <td> 123 (5%)</td>
            <td> 40 (4%)</td>
            <td> 388 (5%)</td>
        </tr>
        <tr>
            <th rowspan=3><em>All Tracks</em></th>
            <th>Avg</th>
            <td>1.66</td>
            <td>2.66</td>
            <td>3.66</td>
            <td>4.66</td>
            <td>5.66</td>
            <td>6.66</td>
            <td>7.66</td>
            <td>8.66</td>
        </tr>
        <tr>
            <th>Stddev</th>
            <td> ± 0.1</td>
            <td>± 0.2</td>
            <td>± 0.3</td>
            <td>± 0.4</td>
            <td>± 0.5</td>
            <td>± 0.6</td>
            <td>± 0.7</td>
            <td>± 0.8</td>
        </tr>
        <tr>
            <th>Abs (%)</th>
            <td> 2 (4%)</td>
            <td> 10 (3%)</td>
            <td> 25 (5%)</td>
            <td> 265 (6%)</td>
            <td> 15 (4%)</td>
            <td> 123 (5%)</td>
            <td> 40 (4%)</td>
            <td> 388 (5%)</td>
        </tr>
    </tbody>
</table>

WDYT ?

**Comment by fcamblor** [comment]
ping @aheritier : I can do something for this if you think it can bring some value prior to the review meeting

**Comment by aheritier** [comment]
+1 @fcamblor Nice idea.
But don't take too much time, you already did a lot

**Comment by fcamblor** [comment]
This change will have a performance impact on the myvotes screen rendering, as it would require to load every Reviews from Redis which may impact the memory consumption / usage

@nicmarti will not be happy :-)

**Comment by fcamblor** [comment]
I think we can close it as it has been somewhat implemented in #304
