### ISSUE TITLE
Include company name in speaker REST call

### ISSUE THREAD

**Issue by stephanj** [nicmarti/cfp-devoxx#24]
Hey,

Please include the company name in the following speakers REST call : 

http://cfp.devoxx.be/api/conferences/DV15/speakers

This will allow us (using only one call) to show the list of speakers and their company in the mobile apps. 

Thanks in advance,

Stephan

**Comment by nicmarti** [comment]
I also added twitter
This is live for FR, and can be cherry-pick to Belgium if you want. Just ask Louis to do it.
Thanks
