### ISSUE TITLE
The link to the Talk types' FAQ is broken

### ISSUE THREAD

**Issue by danielpetisme** [nicmarti/cfp-devoxx#27]
Since a picture is worth a thousand words, I give you 2 pictures (roughly equivalent to 2000 words) :smile: 

When your of the proposal form, you've a link on your right about the **Talk types FAQ**
![1](https://cloud.githubusercontent.com/assets/593564/12684238/140516fa-c6be-11e5-8017-c8b13986e22b.png)
If you click on it, it fails. The URL is: http://www.devoxx.fr/dvxfr15-faq-2#format.
![2](https://cloud.githubusercontent.com/assets/593564/12684240/17857536-c6be-11e5-9faa-f83be8046049.png)

**Comment by nicmarti** [comment]
thanks
