### ISSUE TITLE
Golden Ticket - Open for review button missing on HoL & Quickies

### ISSUE THREAD

**Issue by dcuenot** [nicmarti/cfp-devoxx#271]
Hello,

When I go to "all my votes" page, I can see I have remaining Quickies & HoL, however the `Open for review` button is missing.

As usual, it's easier with screenshots:
* Quickies -> no button
<img width="756" alt="image" src="https://user-images.githubusercontent.com/11711525/148963989-c9668894-22f4-4dc1-97ee-9ac4a989a5a5.png">

* HoL -> no button
<img width="743" alt="image" src="https://user-images.githubusercontent.com/11711525/148964049-50379a26-5d1b-4bf5-8ccb-10f1a5e01362.png">

* TiA -> Button is here
<img width="748" alt="image" src="https://user-images.githubusercontent.com/11711525/148964159-e541b1fe-aefd-4b36-84f8-6cfd2ba7b2ec.png">

And according to the email, we have until 24th January to vote, so I think I'm still in the good timing :)

Good luck for the fix
Damien

**Comment by aheritier** [comment]
Hi @dcuenot thanks for reporting this issue.


The button is displayed only if there are some proposals to review in the current track you selected (Architecture in your screenshot). If you click on all tracks you should see the button.

But there is a bug and I think we should update the text/numbers to match what is filtered. 
When we are in a track with 0 reviews to do, the text is displaying the number of reviews to do 

@fcamblor WDYT ?

**Comment by fcamblor** [comment]
💯 with this, not sure to understand how it went like this but your diagnostic is accurate Arnaud :)

As a side note, I'm wondering if we shouldn't show the "Open for review" button (with maybe a different label) when some review remains for selected type and 0 review remain for selected type+track.

**Comment by dcuenot** [comment]
Got it @aheritier!
Indeed when I select "All tracks" the button is back. Thanks for the explanations
