### ISSUE TITLE
Page my votes, tableaux vides sans propositions

### ISSUE THREAD

**Issue by lilian-benoit** [nicmarti/cfp-devoxx#28]
Les propositions où j'ai voté ne s'affichent plus dans la page my votes.
Voici une capture d'écran : 
![devoxx_cfp](https://cloud.githubusercontent.com/assets/6814443/12699322/a2629572-c7b7-11e5-9ba2-8b94540b2313.png)

**Comment by nicmarti** [comment]
Fixed, thanks for reporting
