### ISSUE TITLE
Golden ticket: until when can we vote?

### ISSUE THREAD

**Issue by dcuenot** [nicmarti/cfp-devoxx#284]
Hi,

I'm a bit confused by the date displayed on CFP GT homepage.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/11711525/150875304-dd108339-22e5-4346-ac8a-9d979bb8a381.png">

30th January is not a Tuesday but a Sunday this year.
Or if it's until Tuesday 25th January I will have to rush to finish to vote ^^

Thanks for your help.
Regards

Damien

**Comment by aheritier** [comment]
Hi Damien

Effectively there is an error. I think Nicolas sent an email about our dates. The deadline for conferences votes is Sunday 30th (we start to choose them by Monday 31st). 

The deadline for others types was today (but we'll revisit our choices in the next two weeks)

**Comment by dcuenot** [comment]
Ok perfect :) Thanks for the clarification

I have the entire week to review my 290 remaining conferences.

**Comment by aheritier** [comment]
@dcuenot thanks a lot for your help !!
