### ISSUE TITLE
Add "approved by" graphs on leaderboard page

### ISSUE THREAD

**Issue by aheritier** [nicmarti/cfp-devoxx#35]
For now we have 
- Submitted by Track + Submitted by Type : for statistics about all submitted proposals
- Accepted by Track + Accepted by Type : for statistics about all proposals accepted by speakers

I would love to see the same data with Approved proposals to give us an idea of what the program team approved (and which aren't yet accepted by speakers)

Cheers

**Comment by nicmarti** [comment]
Implemented
