### ISSUE TITLE
All speakers with one approved talk, grouped by Company

### ISSUE THREAD

**Issue by aheritier** [nicmarti/cfp-devoxx#36]
It would be better if they can be grouped and sorted by decreasing number of talks

**Comment by aheritier** [comment]
https://cfp.devoxx.fr/cfpadmin/allSpeakers/byProposals/byCompany 
https://cfp.devoxx.fr/cfpadmin/allSpeakers/approvedTalks/byCompany 

Fixed ?

**Comment by nicmarti** [comment]
Fixed
https://cfp.devoxx.fr/cfpadmin/leaderboard/proposals/companies
