### ISSUE TITLE
Private notes added to Speaker

### ISSUE THREAD

**Issue by zdanek** [nicmarti/cfp-devoxx#37]
There can be private notes added to particular talk, but not to a speaker. It would be convenient to have ability to add a note to a speaker so the program committee could exchange some thoughts on the speaker.

**Comment by nicmarti** [comment]
Thanks for the suggestion, will do that for FR and UK 2017.

**Comment by nicmarti** [comment]
Still not implemented :-( 
But we're working also on a Tag feature
