### ISSUE TITLE
Show all speakers page should use 'cleanTwitter' instead of 'twitter' field

### ISSUE THREAD

**Issue by royvanrijn** [nicmarti/cfp-devoxx#42]
If I'm correct the showAllSpeakers.scala.html page can be improved a tiny bit. Instead of listing ".twitter" for the speakers, it might be better to show ".cleanTwitter" to have consistency throughout?

(just a tiny improvement)

Normally I would submit a pull request, but I'm not near a computer with Scala atm so I can't test this, it seems trivial enough though.

**Comment by nicmarti** [comment]
Fixed :-)
