### ISSUE TITLE
Markdown does double escaping

### ISSUE THREAD

**Issue by emmanuelbernard** [nicmarti/cfp-devoxx#43]
When I type the following in my abstract

```
This is an `Optional<T>`, and some `List<@Email String>` emails.
```

The output is doubly escaped and the `<` are rendered as `&lt;`:

```
This is an Optional&lt;T&gt;, and some List&lt;@Email String&gt; emails.
```

Other Markdown renderers out there like Trello or GitHub don't do this and properly display `<`

**Comment by ybonnel** [comment]
There is an escape before transform :
https://github.com/nicmarti/cfp-devoxx/blob/dev/app/models/Proposal.scala#L158

**Comment by nicmarti** [comment]
Bug, I should re-introduce @Html in the view template (as the content is escaped when one create a Proposal)
Thanks for reporting

**Comment by nicmarti** [comment]
fixed
