### ISSUE TITLE
Add langage info in talk detail view and votes list

### ISSUE THREAD

**Issue by aheritier** [nicmarti/cfp-devoxx#51]
https://cfp.devoxx.fr/cfpadmin/allvotes/all
https://cfp.devoxx.fr/cfpadmin/proposal/TLU-1974

Useful only for devoxx MA and FR where we are receiving talks in several langages

**Comment by nicmarti** [comment]
If ConferenceDescriptor.current().frLangEnabled then show Flag + Proposal.lang on the proposal view as suggested
