### ISSUE TITLE
Fix email threads

### ISSUE THREAD

**Issue by aheritier** [nicmarti/cfp-devoxx#53]
* a unique thread/title must be used per proposal for all notifications (creation, new public comment, new private comment, ...). Something like: [ID] Subject
* Don't mix threads for private messages. For now all PM from a CFP users for any proposals are in the same thread

**Comment by nicmarti** [comment]
I'm working on it and it's partially implemented.

Anyone interested by this feature will need to switch from Mailjet to Mailgun. The first provider does not let you set the Message-ID. Thus it's almost impossible to create a clean thread of mail.
I updated and implemented a simple system where I store to Redis the last Message-ID for a particular thread. This is used to set the "In-Reply-To" RFC 822 field in the 2nd email, and create the conversation.

**Comment by nicmarti** [comment]
Fully implemented and deployed on FR

See https://github.com/nicmarti/cfp-devoxx/commit/29cd3dbacb8d0a9cd610ef49d7b67302f0bedfcb
