### ISSUE TITLE
REST service to get all talks no longer works

### ISSUE THREAD

**Issue by ge0ffrey** [nicmarti/cfp-devoxx#54]
For DevoxxBe, going to this url used to get a list of all tasks used to work for Devoxx 2014, but doesn't work for 2016:
  http://cfp.devoxx.be/api/conferences/DV16/talks

I use that url in an open source prototype to build an optimal schedule builder called optaconf:
  https://github.com/ge0ffrey/optaconf

**Comment by nicmarti** [comment]
This is related to Devoxx 2016
