### ISSUE TITLE
Convert a submitted talk to a sponsor talk

### ISSUE THREAD

**Issue by pauleveritt** [nicmarti/cfp-devoxx#57]
I'm a developer advocate at JetBrains. I submitted "TypeScript 2.0 and Failing Sooner" as a conference talk but it was rejected. JetBrains is a sponsor and has two sponsor talks, and asked me to re-submit mine as a sponsored talk. However, the editing screen doesn't have the orange envelope-send icon, presumably because the CFP is closed.

How do I submit a sponsored talk?

**Comment by nicmarti** [comment]
You need to contact the program team directly (here Devoxx Belgium I presume)
