### ISSUE TITLE
Can't sign up to CFP

### ISSUE THREAD

**Issue by GTechene** [nicmarti/cfp-devoxx#64]
* Go to http://cfp.devoxx.fr/signup
* Fill in the form with correct information
* You end up on the page http://cfp.devoxx.fr/newspeaker stating :

"Success!
We just sent you an email so that you can validate your email address.

Your access code is generated and is displayed once you validate your email.

You will then be able to log-in and start to use the Devoxx FR 2017 CFP CFP web site."

Expected : receive an e-mail as stated.
Actual : nothing was received.

I have tried 3 times, same account, nothing happens. Destination e-mail address is free.fr

**Comment by nicmarti** [comment]
Hi
Can you please contact me by email?
This is not a bug but a support issue.
Thanks
