### ISSUE TITLE
Can't remove filter

### ISSUE THREAD

**Issue by bric3** [nicmarti/cfp-devoxx#65]
In the admin part, when I click on a theme to filter submissions on that theme, I can't remove the filter, button has no effect.

https://cfp.devoxx.fr/cfpadmin

<img width="892" alt="screen shot 2017-01-07 at 14 28 20" src="https://cloud.githubusercontent.com/assets/803621/21741999/ce52e970-d4e5-11e6-8156-6891c6e2f5eb.png">

**Comment by nicmarti** [comment]
confirmed

**Comment by nicmarti** [comment]
Fixed, thanks
