### ISSUE TITLE
videos do not always display

### ISSUE THREAD

**Issue by GabrielKast** [nicmarti/cfp-devoxx#67]
on cfp.devoxx.fr Here : http://cfp.devoxx.fr/cfpadmin/proposal/SEQ-9834 the youtbue display does not work. But here for instance it works : http://cfp.devoxx.fr/cfpadmin/proposal/PFW-2524
Maybe it depends on the url provided by the speaker, maybe because youtube proposes several urls. I don't know but i though it was worth do a little dive into that issue

**Comment by nicmarti** [comment]
I added the link to the Video as it was entered by the speaker.

For your 2 tests, the first one de-activated the "embedded" authorization => this is why we cannot play the video.

Fixed and will be ok for Devoxx FR 2018
