### ISSUE TITLE
LinkedIn login does not work

### ISSUE THREAD

**Issue by jacquesgiraudel** [nicmarti/cfp-devoxx#70]
Error : invalid redirect_uri. This value must match a URL registered with the API Key.

**Comment by akinsella** [comment]
Hello,

There is a typo in configuration variables declared in application.conf file, it may help (or not) to fix it in configuration file: LINKEDIN_CLIEND_ID => LINKEDIN_CLIENT_ID

**Comment by nicmarti** [comment]
Fixed, sorry for that
