### ISSUE TITLE
Can't connect with my cfp account

### ISSUE THREAD

**Issue by larousso** [nicmarti/cfp-devoxx#77]
Hi, 

I followed the instructions from the mail to restore my profile : 
To restore your profile : 
- logout from the CFP
- go to my.devoxx.fr
- authenticate, use the same email as the one you used on the CFP
- go back to the CFP Agenda
- select a talk to build your agenda => now it works
- go back to the home page for speaker => now it works

When I log in, the cfp ask me to create a new speaker account. 
My account was created with the address alexandre.delegue@serli.com. 

Thanks for your support, 
Alexandre

**Comment by ncomet** [comment]
same problem here, I lost sync with my github (-)  I could not connect anymore and it created another account... I lost the account related to my talk infos.

Thanks for the tip Alexandre, the workaround did the job.

**Comment by nicmarti** [comment]
Should be now fixed. For a while we suffered from an oauth issue, that leads to the creation of a 2nd profile for the very same email. We can't automatically fix old web users so if you still have this issue, please contact info@devoxx.fr and we will manually fix it.
