### ISSUE TITLE
"Sorry, cannot import your github profile. The e-mail is not found."

### ISSUE THREAD

**Issue by greenjoe** [nicmarti/cfp-devoxx#79]
Hello,
when trying to sign in via github on the cfp webpage I get
"Sorry, cannot import your github profile. The e-mail is not found. You might want to change your github settings on https://github.com/settings/profile."
However I can login via github when using the mobile app without any issues and I only have one github account.

**Comment by dvtoever** [comment]
Issue still persists

**Comment by martinsson** [comment]
Same here

**Comment by nicmarti** [comment]
Hi, can you please specify which CFP you're trying to use ? France ? UK ? Poland or USA ? 
I just need the URL thanks

**Comment by martinsson** [comment]
Hi. It's the French one http://cfp.devoxx.fr/home

**Comment by dvtoever** [comment]
You might try to check your github settings https://github.com/settings/emails and make sure that "Keep my email address private" is not checked

**Comment by martinsson** [comment]
It's unselected. Here's a screen shot of my settings

<img width="783" alt="prefs" src="https://user-images.githubusercontent.com/182208/34666480-e9f56abe-f464-11e7-9da4-abf0b7a47e5a.png">

Please tell me if I can be of any more help

**Comment by nicmarti** [comment]
Hi
What if you go on Github to https://github.com/settings/applications ? Then do you see DevoxxFR CFP ? If yes, you should be able to select it and see something like this 


![capture d ecran 2018-01-08 a 20 17 24](https://user-images.githubusercontent.com/157075/34688023-fe548bc4-f4b0-11e7-9dee-2f10add39a73.png)

**Comment by martinsson** [comment]
Hi, 
I have exactly that 
<img width="763" alt="settings for devoxx cfp" src="https://user-images.githubusercontent.com/182208/34693171-f8b5e516-f4c2-11e7-9b3e-2d7af0d23d9f.png">

**Comment by martinsson** [comment]
An observation, I revoked the access then tried to register again, and I got the same error. With a bit of luck this is a way to reproduce the issue, for anyone.

**Comment by stephanie-walter** [comment]
Hi,
I got the exact same issue as @martinsson, the email private is unchecked, I also tried revoking the acces, nothing works the error message is still here :(

**Comment by aheritier** [comment]
@stephanie-walter also to authenticate on cfp.devoxx.fr with GitHub ?

**Comment by stephanie-walter** [comment]
@aheritier I finally gave up and used G+ :/

**Comment by aheritier** [comment]
ok @stephanie-walter I don't understand we have a serious issue with GitHub but it seems to not impact everyone
