### ISSUE TITLE
Exception while build with Docker 

### ISSUE THREAD

**Issue by taliptayfur** [nicmarti/cfp-devoxx#83]
When i use docker to build the project without any modifications to config files. It gaves me exception error. I have minimal knowledge to project and can't figure out the what was the problem. 

`| java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
play_1           | 	at scala.reflect.internal.util.Position.start(Position.scala:114)
play_1           | 	at sbt.internals.parser.SbtParser.sbt$internals$parser$SbtParser$$convertStatement$1(SbtParser.scala:148)
play_1           | 	at sbt.internals.parser.SbtParser$$anonfun$4.apply(SbtParser.scala:153)
play_1           | 	at sbt.internals.parser.SbtParser$$anonfun$4.apply(SbtParser.scala:153)
play_1           | 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
play_1           | 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
play_1           | 	at scala.collection.immutable.List.foreach(List.scala:318)
play_1           | 	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
play_1           | 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
play_1           | 	at sbt.internals.parser.SbtParser.splitExpressions(SbtParser.scala:153)
play_1           | 	at sbt.internals.parser.SbtParser.<init>(SbtParser.scala:58)
play_1           | 	at sbt.EvaluateConfigurations$.splitExpressions(EvaluateConfigurations.scala:226)
play_1           | 	at sbt.EvaluateConfigurations$.parseConfiguration(EvaluateConfigurations.scala:69)
play_1           | 	at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:106)
play_1           | 	at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:712)
play_1           | 	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:717)
play_1           | 	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:716)
play_1           | 	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
play_1           | 	at scala.collection.AbstractMap.getOrElse(Map.scala:58)
play_1           | 	at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:716)
play_1           | 	at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:723)
play_1           | 	at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:723)
play_1           | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
play_1           | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
play_1           | 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
play_1           | 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
play_1           | 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
play_1           | 	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
play_1           | 	at sbt.Load$.loadFiles$1(Load.scala:723)
play_1           | 	at sbt.Load$.discoverProjects(Load.scala:734)
play_1           | 	at sbt.Load$.discover$1(Load.scala:545)
play_1           | 	at sbt.Load$.loadTransitive(Load.scala:574)
play_1           | 	at sbt.Load$.loadProjects$1(Load.scala:442)
play_1           | 	at sbt.Load$.loadUnit(Load.scala:446)
play_1           | 	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
play_1           | 	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
play_1           | 	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
play_1           | 	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
play_1           | 	at sbt.BuildLoader.apply(BuildLoader.scala:140)
play_1           | 	at sbt.Load$.loadAll(Load.scala:334)
play_1           | 	at sbt.Load$.loadURI(Load.scala:289)
play_1           | 	at sbt.Load$.load(Load.scala:285)
play_1           | 	at sbt.Load$.load(Load.scala:276)
play_1           | 	at sbt.Load$.apply(Load.scala:130)
play_1           | 	at sbt.Load$.buildPluginDefinition(Load.scala:821)
play_1           | 	at sbt.Load$.buildPlugins(Load.scala:787)
play_1           | 	at sbt.Load$.plugins(Load.scala:775)
play_1           | 	at sbt.Load$.loadUnit(Load.scala:431)
play_1           | 	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
play_1           | 	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
play_1           | 	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
play_1           | 	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
play_1           | 	at sbt.BuildLoader.apply(BuildLoader.scala:140)
play_1           | 	at sbt.Load$.loadAll(Load.scala:334)
play_1           | 	at sbt.Load$.loadURI(Load.scala:289)
play_1           | 	at sbt.Load$.load(Load.scala:285)
play_1           | 	at sbt.Load$.load(Load.scala:276)
play_1           | 	at sbt.Load$.apply(Load.scala:130)
play_1           | 	at sbt.Load$.defaultLoad(Load.scala:36)
play_1           | 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
play_1           | 	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
play_1           | 	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
play_1           | 	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
play_1           | 	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
play_1           | 	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
play_1           | 	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
play_1           | 	at sbt.Command$.process(Command.scala:92)
play_1           | 	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
play_1           | 	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
play_1           | 	at sbt.State$$anon$1.process(State.scala:184)
play_1           | 	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
play_1           | 	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
play_1           | 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
play_1           | 	at sbt.MainLoop$.next(MainLoop.scala:98)
play_1           | 	at sbt.MainLoop$.run(MainLoop.scala:91)
play_1           | 	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
play_1           | 	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
play_1           | 	at sbt.Using.apply(Using.scala:24)
play_1           | 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
play_1           | 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
play_1           | 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
play_1           | 	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
play_1           | 	at sbt.StandardMain$.runManaged(Main.scala:53)
play_1           | 	at sbt.xMain.run(Main.scala:28)
play_1           | 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
play_1           | 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
play_1           | 	at xsbt.boot.Launch$.run(Launch.scala:57)
play_1           | 	at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
play_1           | 	at xsbt.boot.Launch$.launch(Launch.scala:65)
play_1           | 	at xsbt.boot.Launch$.apply(Launch.scala:16)
play_1           | 	at xsbt.boot.Boot$.runImpl(Boot.scala:32)
play_1           | 	at xsbt.boot.Boot$.main(Boot.scala:21)
play_1           | 	at xsbt.boot.Boot.main(Boot.scala)
play_1           | [error] java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
play_1           | [error] Use 'last' for the full log.
`

**Comment by h3xstream** [comment]
I have the same stacktrace.

**Comment by nicmarti** [comment]
I don't think the Docker version is up-to-date. I don't use it so I need a bit of help for this one.
