### ISSUE TITLE
Typo in Leaderboard screen

### ISSUE THREAD

**Issue by jeanlaurent** [nicmarti/cfp-devoxx#94]
`Stats are computed every 10 minuts` <-- missing an e

<img width="239" alt="screen shot 2017-11-28 at 14 17 38" src="https://user-images.githubusercontent.com/197016/33321719-fb91b77a-d446-11e7-8e40-6f2f60c2f9d1.png">

**Comment by aheritier** [comment]
et même pas une petite PR ??

**Comment by aheritier** [comment]
c'est bien parceque c'est toi @jeanlaurent
