### ISSUE TITLE
Stats are *not* calculated every 10 minutes

### ISSUE THREAD

**Issue by jeanlaurent** [nicmarti/cfp-devoxx#96]
Stats are obviously *not* updated every 10 minutes or even 10 minuts. see ( #94 )
They are atm only refreshed when a manual trigger is issued through the leaderboard screen.

**Comment by aheritier** [comment]
Ouai je pense que tu as raison. Faut que je regarde.

**Comment by nicmarti** [comment]
Correct. First version was really with a cron but this code was deleted. I need to update the Actor part of the CFP and I'll fix that.

**Comment by nicmarti** [comment]
Should have been fixed. This was a Clevercloud missconfiguration => the scheduler was off.

Just let me know but it should now be ok
